### PR TITLE
chore: Update Header component and fix a tiny bug

### LINKED ISSUE #3: Create basic Header component as example pull request.
- Include example use of Storybook

### PR DESCRIPTION
**Pull request by yuyu0227**
### Description
1. Update Header component (menu bar and login button) using material-ui
2. fix inconsistent "spring.datasource.url" property in application-dev.properties, the url should be "...mcitmocks-dev" but not "...mcitmocks_dev"

### Testing
Run both locally

### Checklist
- [x] I provided a description of the contents of this pull request.
- [x] I've linked this pull request to an issue.
- [x] I've assigned myself as the Assignee and labelled the PR correctly.

### CODE REVIEW

**Comment by wilsonplau** [comment]
Could you briefly explain why you used Material UI for this?

**Comment by wilsonplau** [comment]
(Also, the reason why we separate non-related issues in separate PRs is because we can probably merge the config fix, but the header stuff is probably in conflict with: https://github.com/mcitcentral/mcitmocks/pull/2

**Comment by yuyu0227** [comment]
> (Also, the reason why we separate non-related issues in separate PRs is because we can probably merge the config fix, but the header stuff is probably in conflict with: #2

I see

**Comment by yuyu0227** [comment]
> Could you briefly explain why you used Material UI for this?

Material UI provides some easy implementation for nav bar and utils, and I saw you chose a material-theme design in Figma  https://www.figma.com/file/oNWss4AVW2GWsk9K9MEfLa/mcitmocks?node-id=11%3A2, which is consistent with Material UI

**Pull request closed without merging**
